# Generated by Django 3.0.1 on 2020-12-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('qnty', models.IntegerField(default=1)),
                ('prod_id', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Cart')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
