# Generated by Django 3.0.1 on 2020-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20201216_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='cart_name',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
