# Generated by Django 3.0.1 on 2020-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_cartitems_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
