# Generated by Django 3.0.1 on 2020-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20201216_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='final_price',
            field=models.IntegerField(default=100),
        ),
    ]
