# Generated by Django 3.0.1 on 2020-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_cartitems_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='final_price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
